version: '3'

services:
  nginx-rtmp:
    container_name: nginx-rtmps
    hostname: nginx-rtmps
    image: viertelwissen/nginx-rtmps
    ports:
      - "1935:1935/tcp"
      - "8080:8080/tcp"
    restart: always
    #volumes:
      #- ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      TZ: "Europe/Berlin"
      #WEB_USER: username
      #WEB_PASSWORD: password
      #APPLICATION_NAME: "secretName-default:live"
      #TWITCH_KEY: ""
      #YOUTUBE_KEY: ""
      #TROVO_KEY: ""
      #FACEBOOK_KEY: ""
      #INSTAGRAM_KEY: ""
      #DEBUG: "true"
      